### ISSUE TITLE
Dropdown has no scroll if larger than window size

### ISSUE THREAD

**Issue by wilsonk** [david-vanderson/dvui#21]
I just added a dropdown and filled it with a lot of items, but i can't see the bottom several items, even in full screen mode, therefore I can't choose those items. If I use the down key then the highlighter just disappears of the bottom of the screen also.

Perhaps there is an option I am unaware of...or I should be wrapping the dropdown?

**Comment by david-vanderson** [comment]
Sorry - you ran into something I haven't gotten to yet.  Dropdown scrolling and keyboard navigation both need implementation.  Thanks for filing the issue!

**Comment by david-vanderson** [comment]
I committed code to enable scrolling (both for dropdowns and popup menus).  Does that work for you?

I still need to work on the keyboard navigation.

**Comment by wilsonk** [comment]
Yes, that works. Thanks. Should I close or wait for keyboard navigation, as a reminder?

**Comment by david-vanderson** [comment]
Sorry - should have said.  Let's leave it open as a reminder.  Thanks!

**Comment by david-vanderson** [comment]
I made keyboard nav work better (and also scroll to show menu items).  Is that working for you?

**Comment by wilsonk** [comment]
Yes, it is working pretty well here. One small issue is that when the number of entries in a dropdown exceeds the size of the window, a nice scroll bar appears as it should, but as you use a down arrow key to move the highlight down, the list scrolls up slightly if you get too close to the bottom of the list.

This feature is fine, but this highlight moving appears to break somewhat because the highlighted item moves up slightly as you scroll lower, then the highlight goes off the bottom of the menu and reappears at the top of the dropdown, moves until you get near the bottom of the list again, then the 'auto-scroll-up' feature runs again, and the highlight goes off the bottom of the dropdown again.

Scrolling and picking/highlighting with the mouse works fine, though.

**Comment by david-vanderson** [comment]
Thanks for testing!  I don't think I understand what you mean.

When a menu item is highlighted, it should scroll so that it is wholly visible.  If a menu item is half-off the bottom of the scroll viewport, when it is highlighted it will move up to be fully visible.  Is that what you mean by "moves up slightly as you scroll lower"?

Or are you saying you don't think the list should scroll at all to show the highlighted item?

I also just noticed that holding the down arrow (so you get repeat keys) was not handled well - the keydown changes the selected item but the repeats scroll the container.  I've fixed that (so now holding the down key should cycle through all the items).

**Comment by wilsonk** [comment]
The small update for repeating keys seems fine, but it didn't fix my issue.

It's very hard to explain, so you will probably have to test with a dropdown that has 100+ items in it. Then just click on it to open, and use the down arrow key immediately to move the highlighting down...once I get about five items down the in the dropdown list, it 'auto-scrolls' up a little to show more of the list, with regards to the highlight. This seems quite reasonable...though maybe is should only 'auto-scroll' once the highlight gets past half way down (or three quarters maybe).

But then, if you continue to just press (or hold down) the down arrow key, the 'auto-scrolling' part seems to not keep up with the downward highlighting and things go wonky.  The list stops scrolling and the highlight goes off the bottom of the dropdown list and reappears at the top item...then the 'auto-scrolling' gets very wonky and doesn't work very well, so you have to keep 'dropping' off the bottom of the dropdown list to get to the items that you can't see lower down....very strange. 

Like I mentioned, it is probably best if you just fill a big dropdown list and test. This is on Linux, btw. I haven't tested on any other OS.

**Comment by david-vanderson** [comment]
I've been unable to reproduce this.  I committed some fixes to dropdown.  Can you retest?

If you are still having the problem can you post the code?

**Comment by wilsonk** [comment]
Yep, those last changes fixed things. Thanks.

**Comment by david-vanderson** [comment]
Phew!
